package com.example.qriffic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.security.NoSuchAlgorithmException;

/**
 * Test suite for Player class
 */
public class PlayerTest {

    private Player mockPlayer() throws NoSuchAlgorithmException {

        return new Player("Player McPlayerFace");
    }

    @Test
    void testGetters() throws NoSuchAlgorithmException {

        Player mockPlayer = mockPlayer();

        assertEquals("Player McPlayerFace", mockPlayer.getUserId());
        assertNotEquals("Garrett", mockPlayer.getUserId());

        // hash comparison value generated by https://emn178.github.io/online-tools/sha256.html
        assertEquals("83217d452ce8eec422ff2478619a42cafcf3e392a3f43e99dce3e22eac6373df",
                mockPlayer.getSecret());
        assertNotEquals("aaa17d452ce8eec422ff2478619a42cafcf3e392a3f43e99dce3e22eac6373df",
                mockPlayer.getSecret());
    }
}
