package com.example.qriffic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;



/**
 * Test suite for QRCode class
 */
public class QRCodeTest {

    private QRCode mockQRCode() {

        return new QRCode("uyhpOIUYHPDFnklmd;sajfonui893",
                new Location("53.1234", "12.5623"), "Ash");
    }

    @Test
    void testGetters() {

        QRCode mockQRCode = mockQRCode();

        assertEquals(16088668, mockQRCode.getScore());
        assertNotEquals(16000000, mockQRCode.getScore());

        assertEquals(new Location("53.1234", "12.5623").getLongLat(),
                mockQRCode.getLocation().getLongLat());
        assertNotEquals(new Location("53.1234", "12.5643").getLongLat(),
                mockQRCode.getLocation().getLongLat());

        assertEquals("Ash", mockQRCode.getUsername());
        assertNotEquals("Ash Ketchum", mockQRCode.getUsername());

        // SHA256 output generated by https://emn178.github.io/online-tools/sha256.html
        assertEquals("c914133b717c126ecafc5b9b8bd529bcad06d064edc073906a6b83b58bf57e5c",
                mockQRCode.getIdHash());
        assertNotEquals("c914133b717c126ecafc5b9b8bd529bcad06d064edc073906a6b83b58bf57a5c",
                mockQRCode.getIdHash());

        assertEquals("Grand Purple Garrett's Miteergur", mockQRCode.getName());
        assertNotEquals("NAMED MONSTER", mockQRCode.getName());
    }

    @Test
    void testCompareTo() {

        QRCode mockQRCode = mockQRCode();

        assertEquals(0, mockQRCode.compareTo(new QRCode("uyhpOIUYHPDFnklmd;sajfonui893", null, "Ash")));
        assertNotEquals(0, mockQRCode.compareTo(new QRCode("ayhpOIUYHPDFnklmd;sajfonui893",null,  "Ash")));
    }
}
