package com.example.qriffic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.security.NoSuchAlgorithmException;

/**
 * Test suite for Hash class
 */
public class TestHash {

    private Hash mockHash() throws NoSuchAlgorithmException {

        return new Hash("a");
    }

    @Test
    void testGetters() throws NoSuchAlgorithmException {

        Hash mockHash = mockHash();

        // SHA256 output generated by https://emn178.github.io/online-tools/sha256.html
        assertEquals("ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb",
                mockHash.getHash());
        assertNotEquals("ca978112ca1bbdcafac231b39a23dc4da888eff8147c4e72b9807785afee48bb",
                mockHash.getHash());
    }
}
